CREATE TABLE IF NOT EXISTS wf_form_definition (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    form_key VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    `schema` TEXT,
    tenant_id VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
